-- 1. Criar a tabela de usuários
CREATE TABLE tb_users (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                          name VARCHAR(255) NOT NULL,
                          email VARCHAR(255) NOT NULL,
                          password VARCHAR(255) NOT NULL,
                          CONSTRAINT pk_tb_users PRIMARY KEY (id),
                          CONSTRAINT uc_tb_users_email UNIQUE (email)
);

-- 2. Criar a tabela de posts com o relacionamento do usuário
CREATE TABLE db_post (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                         title VARCHAR(255),
                         description VARCHAR(255),
                         data_criacao TIMESTAMP WITH TIME ZONE,
                         category VARCHAR(255),
                         user_id BIGINT NOT NULL, -- Garante que todo post precisa de um autor
                         CONSTRAINT pk_db_post PRIMARY KEY (id),
                         CONSTRAINT fk_db_post_on_user FOREIGN KEY (user_id) REFERENCES tb_users (id)
);
